=== vertx-websocket with Knative does not work with HTTP/2

The xref:reference/extensions/vertx-websocket.adoc[vertx-websocket] extension is supported with Knative, but has important protocol compatibility constraints.

WebSocket connections require the HTTP/1.1 upgrade mechanism and are incompatible with HTTP/2. If your Knative application is intended to accept WebSocket connections, it **must not** allow negotiating the HTTP/2 protocol, or else clients will fail to upgrade to the WebSocket protocol.

This creates an incompatibility with the xref:reference/extensions/grpc.adoc[grpc] extension, which requires HTTP/2.

NOTE: If you need to use gRPC with Knative, you must configure HTTP/2 support.
ifeval::[{doc-show-advanced-features} == true]
See https://docs.redhat.com/en/documentation/red_hat_openshift_serverless/1.31/html/serving/external-and-ingress-routing#using-http2-gRPC_kourier-gateway-service-type[Using HTTP2 and gRPC] for configuration instructions.
endif::[]
ifeval::[{doc-show-advanced-features} == false]
Refer to your platform's Knative documentation for configuration instructions.
endif::[]

To use WebSockets with Knative:

* Ensure your Knative service does not negotiate HTTP/2
* Configure ingress gateways and load balancers to use HTTP/1.1 for WebSocket routes
* Do not enable HTTP/2 support if your application accepts WebSocket connections

For platform-specific configuration, refer to:

ifeval::[{doc-show-advanced-features} == true]
* https://docs.openshift.com/container-platform/4.15/networking/ingress-operator.html[OpenShift Ingress Operator documentation]
endif::[]
ifeval::[{doc-show-advanced-features} == false]
* https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes Ingress documentation]
* https://knative.dev/docs/serving/services/configure-requests/#protocol-selection[Knative protocol selection documentation]
endif::[]
