/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.mina.sftp.it;

import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.smallrye.certs.Format;
import io.smallrye.certs.junit5.Certificate;
import org.apache.camel.quarkus.test.support.certificate.TestCertificates;
import org.apache.camel.quarkus.test.support.sftp.SftpTestResource;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.is;

@TestCertificates(certificates = {
        @Certificate(name = "ftp", formats = {
                Format.PEM }, password = "password"),
        @Certificate(name = "ftp", formats = {
                Format.PKCS12 }, password = "password") })
@QuarkusTest
@QuarkusTestResource(SftpTestResource.class)
class MinaSftpTest {

    @Test
    void loadComponentMinaSftp() {
        /* A simple autogenerated test */
        RestAssured.get("/mina-sftp/load/component/mina-sftp")
                .then()
                .statusCode(200);
    }

    @Test
    public void testMinaSftpComponent() {

        RestAssured.given()
                .contentType(ContentType.TEXT)
                .body("Hello Camel Quarkus MINA SFTP")
                .post("/mina-sftp/create/hello.txt")
                .then()
                .statusCode(201);

        RestAssured.get("/mina-sftp/get/hello.txt")
                .then()
                .statusCode(200)
                .body(is("Hello Camel Quarkus MINA SFTP"));

        RestAssured.put("/mina-sftp/moveToDoneFile/hello.txt")
                .then()
                .statusCode(204);

        RestAssured.get("/mina-sftp/get/hello.txt")
                .then()
                .statusCode(204);

        RestAssured.get("/mina-sftp/get/hello.txt.done")
                .then()
                .statusCode(200)
                .body(is("Hello Camel Quarkus MINA SFTP"));

        RestAssured.delete("/mina-sftp/delete/hello.txt.done")
                .then()
                .statusCode(204);

        RestAssured.get("/mina-sftp/get/hello.txt.done")
                .then()
                .statusCode(204);
    }

}
