Parameters `tikaConfig` and `tikaConfigUri` are not available in quarkus camel tika extension. Configuration
can be changed only via `application.properties`.

While you can use any of the available https://tika.apache.org/1.24.1/formats.html[Tika parsers] in JVM mode,
only some of those are supported in native mode - see the https://quarkiverse.github.io/quarkiverse-docs/quarkus-tika/dev/index.html[Quarkus Tika guide].

Use of the Tika parser without any configuration will initialize all available parsers. Unfortunately as some of them
don't work in the native mode, the whole execution will fail.

In order to make the Tika parser work in the native mode, selection of parsers for initialization should be used.

* `quarkus.tika.parsers` Comma separated list of parsers (abbreviations). There are two predefined parsers:
`pdf` and `odf`.
* `quarkus.tika.parser.*` Adds new parser abbreviation to be used with previous property. Value is the full class of
the parser.

Example of `application.properties`:
[source,properties]
----
quarkus.tika.parsers = pdf,odf,office
quarkus.tika.parser.office = org.apache.tika.parser.microsoft.OfficeParser
----

For more information about selecting parsers see the https://quarkiverse.github.io/quarkiverse-docs/quarkus-tika/dev/index.html[Quarkus Tika guide].

You may need to add the `quarkus-awt` extension to build the native image. For more information, see https://quarkiverse.github.io/quarkiverse-docs/quarkus-tika/dev/index.html[Quarkus Tika guide].

