/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.cxf.it;

import java.net.URI;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import com.helloworld.service.PersonRequestType;
import com.helloworld.service.PersonResponseType;
import org.apache.camel.CamelContext;
import org.apache.camel.ProducerTemplate;
import org.jboss.logging.Logger;

@Path("/cxf")
@ApplicationScoped
public class CxfResource {

    private static final Logger LOG = Logger.getLogger(CxfResource.class);

    private static final String COMPONENT_CXF = "cxf";

    @Inject
    CamelContext context;

    @Inject
    ProducerTemplate producerTemplate;

    @Path("/load/component/cxf")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public Response loadComponentCxf() throws Exception {
        /* This is an autogenerated test */
        if (context.getComponent(COMPONENT_CXF) != null) {
            return Response.ok().build();
        }
        LOG.warnf("Could not load [%s] from the Camel context", COMPONENT_CXF);
        return Response.status(500, COMPONENT_CXF + " could not be loaded from the Camel context").build();
    }

    @Path("/sendSimpleSoapRequest")
    @GET
    @Consumes(MediaType.WILDCARD)
    @Produces(MediaType.WILDCARD)
    public Response sendSimpleRequest() throws Exception {
        LOG.infof("Sending to cxf: %s", "CamelQuarkusCXF");
        final String response = producerTemplate.requestBody("direct:sendSimpleSoapRequest", "CamelQuarkusCXF", String.class);
        LOG.infof("Got response from cxf: %s", response);
        return Response
                .created(new URI("https://camel.apache.org/"))
                .entity(response)
                .build();
    }

    @Path("/wsSecurity")
    @GET
    @Consumes(MediaType.WILDCARD)
    @Produces(MediaType.WILDCARD)
    public Response wsSecurity() throws Exception {
        LOG.infof("Sending to cxf: %s", "CamelQuarkusCXF");
        final String response = producerTemplate.requestBody("direct:wsSecurity", "CamelQuarkusCXF", String.class);
        LOG.infof("Got response from cxf: %s", response);
        return Response
                .created(new URI("https://camel.apache.org/"))
                .entity(response)
                .build();
    }

    @Path("/sendComplexSoapRequest")
    @GET
    @Consumes(MediaType.WILDCARD)
    @Produces(MediaType.WILDCARD)
    public Response sendComplexSoapRequest() throws Exception {
        PersonRequestType personRequestType = new PersonRequestType();
        personRequestType.setFirstName("Camel Quarkus");
        personRequestType.setLastName("CXF");
        LOG.infof("Sending to cxf: %s", personRequestType);
        final PersonResponseType response = producerTemplate.requestBody("direct:sendComplexSoapRequest", personRequestType,
                PersonResponseType.class);
        LOG.infof("Got response from cxf: %s", response);
        return Response
                .created(new URI("https://camel.apache.org/"))
                .entity(response.toString())
                .build();
    }

    @Path("/soapService")
    @GET
    @Consumes(MediaType.WILDCARD)
    @Produces(MediaType.WILDCARD)
    public Response soapService() throws Exception {
        LOG.infof("Sending to cxf: %s", "CamelQuarkusCXF");
        final String response = producerTemplate.requestBody("direct:helloService", "CamelQuarkusCXF", String.class);
        LOG.infof("Got response from cxf: %s", response);
        return Response
                .created(new URI("https://camel.apache.org/"))
                .entity(response)
                .build();
    }

}
