---
# The format of this file is documented here:
# https://github.com/quarkusio/quarkus-bot#triage-issues
features: [ANALYZE_WORKFLOW_RUN_RESULTS]
workflowRunAnalysis:
  workflows: ["Camel Quarkus CI"]
