=== Pre-load Kamelets at build-time

This extension allows to pre-load a set of Kamelets at build time using the `quarkus.camel.kamelet.identifiers` property.

=== Using the Kamelet Catalog

A set of pre-made Kamelets can be found on the /camel-kamelets/latest[Kamelet Catalog].
To use the Kamelet from the catalog you need to copy their yaml definition (that you can find https://github.com/apache/camel-kamelets/[in the camel-kamelet repo]) on your project in the classpath. Alternatively you can add the `camel-kamelets-catalog` artifact to your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel.kamelets</groupId>
    <artifactId>camel-kamelets-catalog</artifactId>
</dependency>
----

This artifact add all the kamelets available in the catalog to your Camel Quarkus application for build time processing. If you include it with the scope `provided` the artifact should not be part of the runtime classpath, but at build time, all the kamelets listed via `quarkus.camel.kamelet.identifiers` property should be preloaded.
