services:
  - docker
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.m2/wrapper
    - $GRAALVM_HOME
# skip the built-in install step
install: true
script:
  - ./mvnw clean verify -Dnative -Dnative-image.docker-build=true -Dnative-image.xmx=5g -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
