This extension leverages https://github.com/amqphub/quarkus-qpid-jms/[Quarkus Qpid JMS]. A `ConnectionFactory` bean is created automatically
and wired into the AMQP component for you. The connection factory can be configured
via the Quarkus Qpid JMS https://github.com/amqphub/quarkus-qpid-jms#configuration[configuration options].

=== Message mapping with `org.w3c.dom.Node`

The Camel AMQP component supports message mapping between `jakarta.jms.Message` and `org.apache.camel.Message`. When wanting to convert a Camel message body type of `org.w3c.dom.Node`,
you must ensure that the `camel-quarkus-xml-jaxp` extension is present on the classpath.

=== Native mode support for jakarta.jms.ObjectMessage

When sending JMS message payloads as `jakarta.jms.ObjectMessage`, you must annotate the relevant classes to be registered for serialization with `@RegisterForReflection(serialization = true)`.
Note that this extension automatically sets `quarkus.camel.native.reflection.serialization-enabled = true` for you. Refer to the xref:user-guide/native-mode.adoc#serialization[native mode user guide] for more information.

=== Connection Pooling

You can use the `quarkus-pooled-jms` extension to get pooling support for the connections. Refer to the https://quarkiverse.github.io/quarkiverse-docs/quarkus-pooled-jms/dev/index.html[quarkus-pooled-jms] extension documentation for more information.

Just add the following dependency to your `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.messaginghub</groupId>
    <artifactId>quarkus-pooled-jms</artifactId>
</dependency>
----

To enable the pooling support, you need to add the following configuration to your `application.properties`:
[source,properties]
----
quarkus.qpid-jms.wrap=true
----
