#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: custom
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/kamelet.name: "custom-kamelet-resource"
    camel.apache.org/kamelet.version: "v1"
spec:
  definition:
    title: "Number Adder"
    description: "Adds two numbers together"
    properties:
      numberA:
        title: The first number
        description: The first number
        type: int
        default: 1
      numberB:
        title: The second number
        description: The second number
        type: int
        default: 1
  dependencies:
    - "camel:bean"
  template:
    beans:
      - name: additionBean
        type: "#class:org.apache.camel.quarkus.test.support.kamelet.AdditionBean({{numberA}}, {{numberB}})"
    from:
      uri: "kamelet:source"
      steps:
        - to: "bean:{{additionBean}}?method=getResult"
