The xref:{cq-camel-components}::microprofile-metrics-component.adoc[microprofile-metrics] component automatically exposes a set of Camel application metrics. Some of these include:

=== Camel Context metrics

[cols="80,.^20]
|===
|Metric Name | Type

|`camel.context.status`

The status of the Camel Context represented by the `ServiceStatus` enum ordinal

| Gauge

|`camel.context.uptime`

The Camel Context uptime in milliseconds

| Gauge

|`camel.context.exchanges.completed.total`

The total number of completed exchanges

| Counter

|`camel.context.exchanges.failed.total`

The total number of failed exchanges

| Counter

|`camel.context.exchanges.inflight.total`

The total number of inflight exchanges

| Gauge

|`camel.context.exchanges.total`

The total number of all exchanges

| Counter

|`camel.context.externalRedeliveries.total`

The total number of all external redeliveries

| Counter

|`camel.context.failuresHandled.total`

The total number of all failures handled

| Counter

|===

=== Camel Route metrics

[cols="80,.^20]
|===
|Metric Name | Type

|`camel.route.count`

The number of routes

| Gauge

|`camel.route.running.count`

The number of running routes

| Gauge

|`camel.route.exchanges.completed.total`

The total number of completed exchanges for the route

| Counter

|`camel.route.exchanges.failed.total`

The total number of failed exchanges for the route

| Counter

|`camel.route.exchanges.inflight.total`

The total number of inflight exchanges for the route

| Gauge

|`camel.route.exchanges.total`

The total number of all exchanges for the route

| Counter

|`camel.route.externalRedeliveries.total`

The total number of all external redeliveries for the route

| Counter

|`camel.route.failuresHandled.total`

The total number of all failures handled for the route

| Counter
|===

All metrics are tagged with the name of the Camel Context and the id of the route where applicable.

You can also produce your own customized metrics in your Camel routes. For more information, refer to the xref:{cq-camel-components}::microprofile-metrics-component.adoc[microprofile-metrics] component documentation.

Metrics are exposed to Quarkus as application metrics and they can be browsed at http://localhost:8080/q/metrics/application.
