=== Message mapping with `org.w3c.dom.Node`

The Camel JMS component supports message mapping between `javax.jms.Message` and `org.apache.camel.Message`. When wanting to convert a Camel message body type of `org.w3c.dom.Node`, 
you must ensure that the `camel-quarkus-jaxp` extension is present on the classpath.

=== Native mode support for javax.jms.ObjectMessage

When sending JMS message payloads as `javax.jms.ObjectMessage`, you must annotate the relevant classes to be registered for serialization with `@RegisterForReflection(serialization = true)`. 
Note that this extension automatically sets `quarkus.camel.native.reflection.serialization-enabled = true` for you. Refer to the xref:user-guide/native-mode.adoc#serialization[native mode user guide] for more information.

=== Support for Connection pooling and X/Open XA distributed transactions
ifeval::[{doc-show-extra-content} == true]

[NOTE]
====
Connection pooling is a Technical Preview feature in this release of {ProductName}.

To use connection pooling in the `camel-quarkus-jms` components, you must add `io.quarkiverse.artemis:quarkus-artemis` and `io.quarkiverse.messaginghub:quarkus-pooled-jms` to your pom.xml and set the following configuration:
----
quarkus.pooled-jms.max-connections = 8
----
====

endif::[]

You can use the `quarkus-pooled-jms` extension to get pooling and XA support for JMS connections. Refer to the https://quarkiverse.github.io/quarkiverse-docs/quarkus-pooled-jms/dev/index.html[quarkus-pooled-jms] extension documentation for more information.
Currently, it only works with `quarkus-artemis-jms` extension. Just add these two dependencies to your `pom.xml`:
[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.messaginghub</groupId>
    <artifactId>quarkus-pooled-jms</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkiverse.artemis</groupId>
    <artifactId>quarkus-artemis-jms</artifactId>
</dependency>
----

Note that pooling is enabled by default.

To enable XA, you need to add the following configuration to your `application.properties`:
[source,properties]
----
quarkus.pooled-jms.xa.enabled=true
----

[NOTE]
====
`clientID` and `durableSubscriptionName` are not supported in pooling connections. If `setClientID` is called on a `reused` connection from the pool, an `IllegalStateException` will be thrown. You will get some error messages such like `Cause: setClientID can only be called directly after the connection is created`
====
