[[contributor-guide]]
= Contributor guide

[[prerequisites]]
== Prerequisites

* `git`
* GraalVM with `native-image` command installed and `GRAALVM_HOME` environment variable set, see
  https://quarkus.io/guides/building-native-image-guide[Building a native executable] section of the Quarkus
  documentation.
* If your are on Linux, `docker` is sufficient for the native mode too. Use `-Pnative,docker` instead of `-Pnative`
  if you choose this option.
* Java 8
* Maven 3.6.2+ (unless you use the Maven Wrapper, a.k.a. `mvnw` available in the source tree).

[[how-to-build]]
== How to build

Checkout the code

[source,shell]
----
$ git clone https://github.com/apache/camel-quarkus.git
$ cd camel-quarkus
----

A fast build without tests:

[source,shell]
----
$ mvn clean install -DskipTests
----

A build with integration tests in the JVM mode only:

[source,shell]
----
$ mvn clean install
----

A build with integration tests in both the JVM mode and the native mode:

[source,shell]
----
$ mvn clean install -Pnative
----


== Create a new extension

1. You should know link:#how-to-build[how to build].

2. Go through the https://quarkus.io/guides/extension-authors-guide[Quarkus extension author's guide] to get an idea
   what is expecting you.

3. Make sure that nobody else works on the same extension already by searching through the
   https://github.com/apache/camel-quarkus/issues[GitHub issues].

4. Let others know that you work on the given extension by either creating a
   https://github.com/apache/camel-quarkus/issues/new[new issue] or asking to assign an existing one to you.

5. Scaffold the necessary Maven modules using `quarkus-maven-plugin`. As an example let's add a new extension for
   supporting an imaginary Camel component `foo-abc`:
+
[source,shell]
----
$ cd camel-quarkus
$ mvn cq:create -N -Dcq.artifactIdBase=foo-abc
----
+
where:
+
* `foo-abc` is the unique part of the new extension's `artifactId` without the `camel-quarkus-` prefix
+
The above sequence of commands does the following:
* It creates three new Maven modules under the `extensions` directory: `camel-quarkus-foo-abc-parent`, `camel-quarkus-foo-abc`
  (a.k.a. the runtime module) and `camel-quarkus-foo-abc-deployment`.
* These three modules are linked where necessary:
** `camel-quarkus-foo-abc-parent` is added to the `<modules>` of `camel-quarkus-extensions`
** `camel-quarkus-foo-abc` is added to the `<dependencyManagement>` of the runtime BOM (Bill of Materials) `poms/bom/pom.xml`
** `camel-quarkus-foo-abc-deployment` is added to the `<dependencyManagement>` of the deployment BOM (Bill of Materials) `poms/bom-deployment/pom.xml`
* It creates a basic `FooAbcProcessor` class in the deployment module.
* It also creates a stub of an integration test module under `integration-tests/foo-abc`.
+
A compilation performed immediately after generating the modules should pass flawlessly but running the tests will fail
because the test project needs to get finished. You need to build `poms/bom` and `poms/bom-deployment` one time first.

6. Review the generated
   `extensions/foo-abc/runtime/src/main/resources/META-INF/quarkus-extension.yaml` file. If you
   see improper description or keyword,
   https://issues.apache.org/jira/secure/CreateIssue!default.jspa[file a new Camel issue] and ask to fix the metadata
   for the given Camel component.
7. Review the dependencies in the generate runtime and deployment modules. In case the given library is supported by
   Quarkus, you may want to add a dependency on the corresponding Quarkus extension.

8. Complete the integration test module under `integration-tests/foo-abc`. Make sure you test both the consumer and the
   producer of the component (if the component supports both). Make sure the tests are passing both in the JVM mode
   (`mvn test`) and in the native mode (`mvn verify -Pnative`).

9. In case of problems, consult the https://quarkus.io/guides/extension-authors-guide[Quarkus extension author's guide],
   ask for help in the given GitHub issue or via https://gitter.im/apache/camel-quarkus[Camel Quarkus chat].

10. If the usage of your new extension differs from the usage of the given Camel component, please add an AsciiDoc page
   under `docs/modules/ROOT/pages/extensions` and document the differences and Quarkus specific configuration options
   there. For our imaginary Camel component `foo-abc` the path of the page would be
   `docs/modules/ROOT/pages/extensions/foo-abc.adoc`. After completing the page, run `mvn clean install -DskipTests`
   from the root of the source tree to add your extension to the autogenerated list of extensions.

11. Before sending a pull request, please make sure you have run the following Maven command from the project root folder:
+
[source,shell]
----
$ mvn process-resources -Pformat
----
+
The above command will perform the following tasks:
+
* Add license headers to the new files
* Re-generate the list of extensions and the Camel Quarkus Catalog
* Sort elements in various POM files properly
+
Review the result visually.

12. Please squash your commits before sending a pull request.

Good luck!

== Promote a JVM Only extension to Native

The directory `extensions-jvm` contains some extensions that need to be tested in link:https://quarkus.io/guides/building-native-image[native mode]. Configuring the link:https://quarkus.io/guides/writing-native-applications-tips[native build] and implementing integration tests of such extensions may open the door to even faster startup and lower footprint.
Please find some guiding steps below to start this quest:

1. Make sure that nobody else works on promoting the same extension by searching through the
   https://github.com/apache/camel-quarkus/issues[GitHub issues].

2. Let others know that you work on promoting the given extension by either creating a
   https://github.com/apache/camel-quarkus/issues/new[new issue] or asking to assign an existing one to you.

3. Select the JVM Only extension to be promoted, for instance the grpc extension like below:
+
[source,shell]
----
$ cd camel-quarkus
$ export EXT='grpc'
----

4. Split the JVM Only extension into `extensions` and `integration-tests` folders, from a shell execute:
+
[source,shell]
----
$ {
   sed -i '/integration-test/d' "extensions-jvm/${EXT}/pom.xml"
   sed -i "/<module>${EXT}<\/module>/d" "extensions-jvm/pom.xml"
   git mv "extensions-jvm/${EXT}/integration-test/" "integration-tests/${EXT}"
   git mv "extensions-jvm/${EXT}" "extensions/${EXT}"
   sed -i -r "s/(.*)activemq(.*)/\1activemq\2\n\1${EXT}\2/g" extensions/pom.xml
   sed -i -r "s/(.*)activemq(.*)/\1activemq\2\n\1${EXT}\2/g" integration-tests/pom.xml
   sed -i "s/camel-quarkus-grpc-parent/camel-quarkus-integration-tests/g" "integration-tests/${EXT}/pom.xml"
   sed -i "s/camel-quarkus-grpc-integration-test/camel-quarkus-integration-test-${EXT}/g" "integration-tests/${EXT}/pom.xml"
   sed -i -r "s/Quarkus :: (.*) :: Integration Test/Quarkus :: Integration Test :: \1/g" "integration-tests/${EXT}/pom.xml"
  }
----

5. Add the native profile at the end of `integration-tests/${EXT}/pom.xml`:
+
[source,xml]
----
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
----

6. Remove the warning link:https://quarkus.io/guides/writing-extensions#build-step-processors[build step] from `extensions/${EXT}/deployment/src/main/java/org/apache/camel/quarkus/component/${EXT}/deployment/${EXT}Processor.java`:
+
[source,java]
----
    /**
     * Remove this once this extension starts supporting the native mode.
     */
    @BuildStep(onlyIf = NativeBuild.class)
    @Record(value = ExecutionTime.RUNTIME_INIT)
    void warnJvmInNative(JvmOnlyRecorder recorder) {
        JvmOnlyRecorder.warnJvmInNative(LOG, FEATURE); // warn at build time
        recorder.warnJvmInNative(FEATURE); // warn at runtime
    }
----

7. Create a native test at `integration-tests/${EXT}/src/test/java/org/apache/camel/quarkus/component/${EXT}/it/${EXT}IT.java`

8. Check `extensions/${EXT}/runtime/src/main/resources/META-INF/quarkus-extension.yaml`:
* Ensure guide is set to `"https://quarkus.io/guides/camel"`
* Ensure keyword `camel` is present
* Remove the `preview` status

9. Add itests to `.github/workflows/pr-build.yaml`, for instance:
+
[source,yaml]
----
- category: Rpc
 test-modules: >
   grpc
----

10. Unify source files format, update docs and rebuild the whole project:
+
[source,shell]
----
mvn clean install -D skipTests -P format
----

11. Build the extension:
+
[source,shell]
----
cd "extensions/${EXT}"
mvn clean install
----

12. Execute integration tests:
+
[source,shell]
----
cd "../../integration-tests/${EXT}"
mvn clean verify -P native
----

13. Now it's time to solve native build issues if any, extend integration tests coverage and perhaps even shifting some treatments
from runtime to build time. The https://quarkus.io/guides/extension-authors-guide[Quarkus extension author's guide] may be a good
ally for this.

14. Please also check the link:#create-a-new-extension[Create a new extension] section as it contains some useful tips for a good contribution.