= Apache Camel extensions for Quarkus

This project aims to bring the awesome integration capabilities of xref:manual::index.adoc[Apache Camel]
and its vast xref:{cq-camel-components}::index.adoc[component library] to the
https://quarkus.io/[Quarkus runtime].

This enables users to take advantage of the performance benefits, https://quarkus.io/vision/developer-joy[developer joy]
and the https://quarkus.io/vision/container-first[container first ethos] that Quarkus provides.

Camel Quarkus provides xref:reference/index.adoc[Quarkus extensions] for many of the Camel components.

Camel Quarkus also takes advantage of the many performance improvements made in Camel 3, which results in a lower memory footprint, less reliance on reflection (which is good for native application support) and faster startup times.

You can xref:user-guide/defining-camel-routes.adoc[define Camel routes] using the Java DSL, XML, Kotlin, Groovy, YAML or JavaScript.

== Where to go next?

* xref:user-guide/index.adoc[User guide]
* xref:contributor-guide/index.adoc[Contributor guide]
* xref:reference/index.adoc[Extensions reference]
