= Apache Camel extensions for Quarkus

[NOTE]
--
This version ({page-component-display-version}) of {page-component-title} depends on:

* xref:{camel-docs-version}@components::index.adoc[Camel] at version {camel-version}
* https://quarkus.io[Quarkus] at version {quarkus-version}

ifdef::lts[This long term service release will be supported until {lts}.]
ifndef::lts[]
ifdef::prerelease[This is the development version of {page-component-title}. It should not be used in production.]
ifndef::prerelease[This release will not be updated, but rather replaced by a new release.]
endif::[]
--

This project aims to bring the awesome integration capabilities of xref:manual::index.adoc[Apache Camel]
and its vast xref:{cq-camel-components}::index.adoc[component library] to the
https://quarkus.io/[Quarkus runtime].

This enables users to take advantage of the performance benefits, https://quarkus.io/developer-joy[developer joy]
and the https://quarkus.io/container-first[container first ethos] that Quarkus provides.

Camel Quarkus provides xref:reference/index.adoc[Quarkus extensions] for many of the Camel components.

Camel Quarkus also takes advantage of the many performance improvements made in Camel 3, which results in a lower memory footprint, less reliance on reflection (which is good for native application support) and faster startup times.

You can xref:user-guide/defining-camel-routes.adoc[define Camel routes] using the Java DSL, XML, Kotlin, Groovy, YAML or JavaScript.

== Where to go next?

* xref:user-guide/index.adoc[User guide]
* xref:contributor-guide/index.adoc[Contributor guide]
* xref:reference/index.adoc[Extensions reference]

== Compatibility Matrix

[caption=]
.Compatibility between {page-component-title} and dependencies
[width="100%",cols="4,2,2,2,1,3",options="header",]
|===
|{page-component-title} Version
|Camel Version
|Quarkus Version
|GraalVM Version
|LTS Until
|Branch
|===

//cannot use top level index.adoc as the page with the query is always omitted.
indexTable::[version="*",relative="reference/index.adoc",cellformats="util.camelQuarkusRef(pageComponentDisplayVersion, pageComponentVersion)|util.camelRef(camelVersion, camelDocsVersion)|util.quarkusRef(quarkusVersion)|util.graalvmRef(graalvmVersion, graalvmDocsVersion)|lts|quarkus.branch(pageComponentVersion)", requires={requires},transform=util.sortCompatibilityItems]
