= Camel Quarkus 3.26.0 Migration Guide

The following guide outlines how to adapt your code to changes that were made in Camel Quarkus 3.26.0.

== `quarkus.camel.dev-ui.update-internal` renamed to `quarkus.camel.dev-ui.update-interval`

Camel Quarkus 3.25.0 introduced new Quarkus Dev UI pages for various Camel Quarkus extensions.
This also came with a configuration property to determine how frequently the pages had their data refreshed.
Unfortunately, there was a typo in the configuration property name.

Any usage of configuration option `quarkus.camel.dev-ui.update-internal`, should be updated to `quarkus.camel.dev-ui.update-interval`.

== `quarkus-hazelcast` removed from `camel-quarkus-hazelcast`

Due to `quarkus-hazelcast` 4.0.0 not being compatible with Quarkus >= 3.26.0, it has been temporarily removed from the `camel-quarkus-hazelcast` extension.

This means that any native support and any `quarkus-hazelcast` specific features are temporarily not supported with `camel-quarkus-hazelcast`.
You can continue to use the extension in JVM mode using the standard `camel-hazelcast` component functionality.

