=== Infinispan client configuration

You can configure Camel Infinispan in one of two ways.

1. Using the relevant Camel Infinispan xref:{cq-camel-components}::infinispan-component.adoc#_component_options[component & endpoint options]

2. Using the https://quarkus.io/guides/infinispan-client#configuration-reference[Quarkus Infinispan extension configuration properties].

More details about these two configuration methods is described below.

=== Camel Infinispan component and endpoint configuration

When using 'pure' Camel Infinispan component and endpoint configuration (I.e where's there's no `quarkus.infinispan-client` configuration set), you *must* disable generation of the default Quarkus Infinispan `RemoteCacheManager` bean by adding the following configuration to `application.properties`.

[source,properties]
----
quarkus.infinispan-client.devservices.create-default-client=false
----

If you wish to take advantage of https://quarkus.io/guides/infinispan-dev-services[Quarkus Dev Services for Infinispan], the Camel Infinispan component can be configured as follows in `application.properties`.

[source,properties]
----
# dev / test mode Quarkus Infinispan Dev services configuration
quarkus.infinispan-client.devservices.port=31222
%dev,test.camel.component.infinispan.username=admin
%dev,test.camel.component.infinispan.password=password
%dev,test.camel.component.infinispan.secure=true
%dev,test.camel.component.infinispan.hosts=localhost:31222

# Example prod mode configuration
%prod.camel.component.infinispan.username=prod-user
%prod.camel.component.infinispan.password=prod-password
%prod.camel.component.infinispan.secure=true
%prod.camel.component.infinispan.hosts=infinispan.prod:11222
----

=== Quarkus Infinispan configuration

When using the https://quarkus.io/guides/infinispan-client#configuration-reference[Quarkus Infinispan extension configuration properties], the Quarkus Infinispan extensions creates and manages a `RemoteCacheManager` bean.

The bean will get automatically autowired into the Camel Infinispan component on application startup.

Note that to materialize the `RemoteCacheManager` beans, you *must* add injection points for them. For example:

[source,java]
----
public class Routes extends RouteBuilder {
    // Injects the default unnamed RemoteCacheManager
    @Inject
    RemoteCacheManager cacheManager;

    // If configured, injects an optional named RemoteCacheManager
    @Inject
    @InfinispanClientName("myNamedClient")
    RemoteCacheManager namedCacheManager;

    @Override
    public void configure() {
        // Route configuration here...
    }
}
----
