=== BeanIO in native mode

==== XML mapping files

When BeanIO configuration is defined in XML files that are read from the classpath.
You must ensure each file is added to the native application image.
To do this, add the `quarkus.native.resources.includes` configuration property to `application.properties`. For example.

[source,properties]
----
quarkus.native.resources.includes=mapping.xml,model/other-mapping.xml
----

More information about selecting resources for inclusion in the native executable can be found at xref:user-guide/native-mode.adoc#embedding-resource-in-native-executable[Embedding resources in native executable].

==== BeanIO Record classes

All classes that participate in BeanIO marshal / unmarshal operations must be registered for reflection.

This can be achieved with the `@RegisterForReflection`
annotation or with configuration property `quarkus.camel.native.reflection.include-patterns`. For example:

[source,java]
----
@RegisterForReflection
public class Employee {
    ...
}
----

Refer to the xref:user-guide/native-mode.adoc#reflection[Native mode] user guide for more information.
