[[fhir]]
= FHIR Extension

*Since Camel Quarkus 0.3.0*

The FHIR extension integrates with the
http://hapifhir.io/[HAPI-FHIR] library which is an open-source implementation of the
http://hl7.org/implement/standards/fhir/[FHIR] (Fast Healthcare Interoperability Resources) specification in Java.

Maven users will need to add the following dependency to their `pom.xml` for this extension.

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-fhir</artifactId>
</dependency>
------------------------------------------------------------

== Usage

The extension supports the Camel https://camel.apache.org/components/latest/fhirJson-dataformat.html[FHIR Json Dataformat], https://camel.apache.org/components/latest/fhirXml-dataformat.html[FHIR XML Dataformat] and https://camel.apache.org/components/latest/fhir-component.html[FHIR Component]. DSTU2, DSTU3 and R4 are supported.

=== Configuration

The https://hapifhir.io/download.html[hapi-fhir] library, on which camel-fhir depends on, heavily uses reflection which affects performance in Quarkus (memory footprint, build time, CPU resources etc...). The following options are provided to improve on this:

[cols="80,.^10,.^10"]
|===
|Configuration property |Type |Default

|`quarkus.camel.fhir.enable-dstu2`

 enables dstu2 resources
|boolean
|`true`

|`quarkus.camel.fhir.enable-dstu3`

 enables dstu3 resources
|boolean
|`true`

|`quarkus.camel.fhir.enable-r4`

 enables r4 resources
|boolean
|`true`

|`quarkus.camel.fhir.enable-r5`

 enables r5 resources
|boolean
|`true`
|===
