[[freemarker]]
= Freemarker Extension

*Since Camel Quarkus 0.3.0*

The Freemarker extension component allows processing a message using a FreeMarker template. This can be ideal when using Templating to generate responses for requests.

Maven users will need to add the following dependency to their `pom.xml` for this extension.

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-freemarker</artifactId>
</dependency>
------------------------------------------------------------

== Usage

The extension provides support for the Camel https://camel.apache.org/components/latest/freemarker-component.html[Freemarker Component].

=== Configuration

The Camel Freemarker extension exposes the following configuration properties.

[cols="80,.^10,.^10"]
|===
|Configuration property |Type |Default

|`quarkus.camel.freemarker.locations`

 Comma-separated list of locations to scan recursively for templates.
|List<String>
|`freemarker/templates`

|`quarkus.camel.freemarker.include-patterns`

 Used for inclusive filtering scanning of Freemarker templates. By default all tree files inside 'locations' will be included.
|List<String>
|`[]`

|`quarkus.camel.freemarker.exclude-patterns`

 Used for exclusive filtering scanning of Freemarker templates. By default none file inside 'locations' will be excluded.
|List<String>
|`[]`
|===
