[[mustache]]
= Mustache Extension

*Since Camel Quarkus 1.0.0-M5*

The mustache extension provides the capability to transform an incoming message using a link:https://mustache.github.io/[Mustache template].

Maven users will need to add the following dependency to their `pom.xml` for this extension.

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-mustache</artifactId>
</dependency>
------------------------------------------------------------

== Usage

The extension provides support for the Camel https://camel.apache.org/components/latest/mustache-component.html[Mustache Component].

=== Configuration

Beyond standard usages described above, a trick is needed when using mustache templates from classpath resources in native mode. In such a situation, one needs to explicitly embed the resources in the native executable by specifying the `include-patterns` option.

For instance, the route below would load the mustache template from a classpath resource named _template/simple.mustache_:
[source,java]
----
from("direct:start").to("mustache://template/simple.mustache");
----

In order to work in native mode the `include-patterns` configuration should be set. For instance, in the `application.properties` file as below :
[source,properties]
----
quarkus.camel.resources.include-patterns = template/*.mustache
----

More information about selecting resources for inclusion in the native executable could be found at xref:native-mode.adoc#embedding-resource-in-native-executable[Embedding resource in native executable].