[[xslt]]
= XSLT Extension

*Since Camel Quarkus 0.4.0*

The XSLT extension allows you to process a message using an XSLT template.

Maven users will need to add the following dependency to their `pom.xml` for this extension.

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel.quarkus</groupId>
    <artifactId>camel-quarkus-xslt</artifactId>
</dependency>
------------------------------------------------------------

== Usage

The extension provides support for the Camel https://camel.apache.org/components/latest/xslt-component.html[XSLT Component].

=== Configuration

To optimize XSLT processing, the extension needs to know the locations of the XSLT templates at build time.
The XSLT source URIs have to be passed via the `quarkus.camel.xslt.sources` property. Multiple URIs can be separated
by comma.

[source,properties]
----
quarkus.camel.xslt.sources = transform.xsl, file:relative/path/to/my/file.xsl, file:/absolute/path/to/my/file.xsl
----

Scheme-less URIs are interpreted as `classpath:` URIs.

[NOTE]
====
The content of the XSLT source URIs is parsed and compiled into Java classes at build time. These Java classes are the
only source of XSLT information at runtime. The XSLT source files may not be included in the application archive at all.
====

[WARNING]
====
the extension does not yet support Java 11.
====