= Bootstrap Camel Quarkus

Camel Quarkus automatically configures and deploys a Camel Context bean which by default is started/stopped according to
the Quarkus Application lifecycle. The configuration step happens at build time during Quarkus' augmentation phase and
it is driven by the Camel Quarkus extensions which can be tuned using Camel Quarkus specific `camel.quarkus.*`
properties. After the configuration is done, a minimal Camel Runtime is assembled and started at
`https://quarkus.io/guides/writing-extensions#bootstrap-three-phases[RUNTIME_INIT]` time.
At that point, any additional configuration should be done using CDI. Below is an example showing how to configure a
Camel Component:

[source,java]
----
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import org.apache.camel.component.log.LogComponent;
import org.apache.camel.support.processor.DefaultExchangeFormatter;

@ApplicationScoped
public class Configurations {
    /**
     * Produces a {@link LogComponent} instance with a custom exchange formatter set-up.
     */
    @Named
    LogComponent log() {
        DefaultExchangeFormatter formatter = new DefaultExchangeFormatter();
        formatter.setShowExchangePattern(false);
        formatter.setShowBodyType(false);

        LogComponent component = new LogComponent();
        component.setExchangeFormatter(formatter);

        return component;
    }
}
----

To configure components and other aspects of Apache Camel through properties, you can add the `camel-quarkus-main`
extension which brings functionalities from https://camel.apache.org/components/latest/others/main.html[Apache Camel
Main] to Camel Quarkus.

In the example below, we perform the same configuration of the Log component via properties like we did above using Java:

[source,properties]
----
camel.component.log.exchange-formtatter = #class:org.apache.camel.support.processor.DefaultExchangeFormatter
camel.component.log.exchange-formtatter.show-exchange-pattern = false
camel.component.log.exchange-formtatter.show-body-type = false
----
