/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.langchain4j.ingest;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingStore;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Any;
import jakarta.enterprise.inject.Instance;
import jakarta.enterprise.inject.literal.NamedLiteral;
import jakarta.inject.Inject;
import org.apache.camel.CamelContextAware;
import org.apache.camel.spi.IdempotentRepository;
import org.jboss.logging.Logger;

/**
 * Translates the extension's configuration model — build-time and runtime properties and
 * {@code @Ingest} builder methods — into upstream {@link IngestPipelineDefinition}s; the routes
 * themselves are generated by the inherited {@link IngestPipelineRouteBuilder}, and the engine
 * lives in the {@code camel-langchain4j-ingest} component. What stays here is the Quarkus DX:
 * CDI bean resolution with its actionable messages, and the configuration-level validations.
 */
@ApplicationScoped
public class IngestRoutes extends IngestPipelineRouteBuilder {

    private static final Logger LOG = Logger.getLogger(IngestRoutes.class);

    @Inject
    IngestBuildTimeConfig buildTimeConfig;

    @Inject
    IngestRunTimeConfig runTimeConfig;

    @Inject
    IngestBuilderPipelines builderPipelines;

    // these injection points also keep an unnamed store or model bean from being removed as
    // unused - nothing else in the application need inject it
    @Inject
    @Any
    Instance<EmbeddingStore<TextSegment>> storeCandidates;

    @Inject
    @Any
    Instance<EmbeddingModel> modelCandidates;

    @Override
    protected List<IngestPipelineDefinition> pipelines() {
        List<IngestPipelineDefinition> definitions = new ArrayList<>();

        // a pipeline may be declared entirely through runtime properties - the documented
        // minimum is a directory and nothing else - so the two config roots are unioned. Keying
        // off the build-time map alone would make that configuration a silent no-op, since
        // SmallRye only materialises a map key for the mapping whose structure a property matches
        Set<String> builderDeclared = builderPipelines.entries().stream()
                .map(IngestBuilderPipelines.Entry::name)
                .collect(Collectors.toSet());
        Set<String> names = new TreeSet<>(buildTimeConfig.pipelines().keySet());
        names.addAll(runTimeConfig.pipelines().keySet());
        names.removeAll(builderDeclared);

        for (String name : names) {
            IngestBuildTimeConfig.PipelineBuildTimeConfig pipeline = buildTimeConfig.pipelines().get(name);
            IngestRunTimeConfig.PipelineRunTimeConfig runtime = runTimeConfig.pipelines().get(name);

            if (runtime != null && !runtime.enabled()) {
                LOG.infof("Ingestion pipeline '%s' is disabled", name);
                continue;
            }

            // a consumer URI says "consume from this"; its absence says "read that directory"
            String uri = pipeline == null ? null : pipeline.source().uri().orElse(null);
            if (uri != null && runtime != null && runtime.source().directory().isPresent()) {
                throw new IllegalStateException("Ingestion pipeline '" + name + "' sets both source.uri ('" + uri
                        + "') and source.directory ('" + runtime.source().directory().get() + "'). A pipeline "
                        + "reads one source: keep the URI, or drop it to read the directory.");
            }

            definitions.add(definition(name, uri, runtime,
                    resolveStore(name, pipeline == null ? null : pipeline.embeddingStore().orElse(null)),
                    resolveModel(name, pipeline == null ? null : pipeline.embeddingModel().orElse(null)),
                    pipeline == null ? IngestBuildTimeConfig.DEFAULT_MAX_SEGMENT_SIZE : pipeline.maxSegmentSize(),
                    pipeline == null ? IngestBuildTimeConfig.DEFAULT_MAX_OVERLAP_SIZE : pipeline.maxOverlapSize(),
                    pipeline == null ? IngestBuildTimeConfig.DEFAULT_EMBEDDING_BATCH_SIZE : pipeline.embeddingBatchSize(),
                    pipeline == null ? IngestBuildTimeConfig.DEFAULT_MAX_DOCUMENT_SIZE : pipeline.maxDocumentSize(),
                    pipeline == null ? null : pipeline.documentSplitter().orElse(null),
                    pipeline == null ? null : pipeline.parser().orElse(null)));
        }

        for (IngestBuilderPipelines.Entry entry : builderPipelines.entries()) {
            IngestPipelineDefinition definition = builderPipeline(entry);
            if (definition != null) {
                definitions.add(definition);
            }
        }
        return definitions;
    }

    /** An {@code @Ingest}-declared pipeline: the builder twin of the configuration path. */
    private IngestPipelineDefinition builderPipeline(IngestBuilderPipelines.Entry entry) {
        String name = entry.name();
        // configuration can still switch a builder-declared pipeline off, and the check precedes
        // the invocation so a disabled pipeline's method never runs
        IngestRunTimeConfig.PipelineRunTimeConfig external = runTimeConfig.pipelines().get(name);
        if (external != null && !external.enabled()) {
            LOG.infof("Ingestion pipeline '%s' (builder) is disabled", name);
            return null;
        }
        // enabled is the one thing configuration may say about a builder pipeline; anything about
        // its source would be quietly overruled by the @Ingest method, so it is an error instead
        // (source.recursive cannot be told apart from its default, so it alone goes undetected -
        // Source.recursive() is its builder twin)
        if (external != null && (external.source().directory().isPresent()
                || external.source().documentId().isPresent()
                || external.source().idempotentRepository().isPresent()
                || external.source().idempotentRepositoryAutoCreate())) {
            throw new IllegalStateException("Ingestion pipeline '" + name + "' is declared in Java, so its source "
                    + "comes from the @Ingest method. Remove quarkus.camel.langchain4j.ingest." + name + ".source.* , or "
                    + "declare the pipeline in configuration instead.");
        }

        IngestPipeline definition = builderPipelines.definition(entry);
        String uri = "file".equals(definition.sourceType()) ? null : definition.sourceUri();
        return definition(name, uri, definition.asRunTimeConfig(),
                resolveStore(name, definition.embeddingStoreName().orElse(null)),
                resolveModel(name, definition.embeddingModelName().orElse(null)),
                definition.maxSegmentSize(),
                definition.maxOverlapSize(),
                definition.embeddingBatchSize(),
                definition.maxDocumentSize(),
                definition.documentSplitterName().orElse(null),
                definition.parser().orElse(null));
    }

    /**
     * One creation path for both declaration styles, mirroring how a builder pipeline provides
     * the same runtime-configuration view the configuration path reads.
     */
    private IngestPipelineDefinition definition(String name, String uri,
            IngestRunTimeConfig.PipelineRunTimeConfig runtime,
            EmbeddingStore<TextSegment> store, EmbeddingModel model,
            int maxSegmentSize, int maxOverlapSize, int embeddingBatchSize, int maxDocumentSize,
            String documentSplitterName, String parser) {

        IngestPipelineDefinition definition;
        if (uri == null) {
            String directory = required(name, runtime == null ? null : runtime.source().directory().orElse(null),
                    "source.directory");
            definition = IngestPipelineDefinition.directory(name, directory)
                    .recursive(runtime.source().recursive());
        } else {
            definition = IngestPipelineDefinition.consumer(name, uri);
        }
        definition.embeddingStore(store)
                .embeddingModel(model)
                .splitter(maxSegmentSize, maxOverlapSize)
                .embeddingBatchSize(embeddingBatchSize);
        if (maxDocumentSize > 0) {
            definition.maxDocumentSize(maxDocumentSize);
        }
        if (documentSplitterName != null) {
            definition.documentSplitter(documentSplitterName);
        }
        if (parser != null) {
            definition.parser(parser);
        }

        String documentId = runtime == null ? null : runtime.source().documentId().orElse(null);
        if (documentId != null) {
            definition.documentId(documentId);
        } else if (uri != null) {
            // the upstream default header follows the design/headers.adoc convention
            // (CamelLangChain4jIngestDocumentId); this extension released the contract as
            // CamelIngestDocumentId in 3.39.0, so the legacy name is pinned here - the
            // compatibility burden stays downstream, where it was created
            definition.documentId(IngestHeaders.DOCUMENT_ID);
        }

        String repositoryName = runtime == null ? null : runtime.source().idempotentRepository().orElse(null);
        boolean autoCreate = runtime != null && runtime.source().idempotentRepositoryAutoCreate();
        if (autoCreate && repositoryName == null) {
            throw new IllegalStateException("Ingestion pipeline '" + name
                    + "' sets source.idempotent-repository-auto-create but no "
                    + "source.idempotent-repository name to create the register under.");
        }
        if (repositoryName != null) {
            IdempotentRepository repository = getContext().getRegistry().lookupByNameAndType(repositoryName,
                    IdempotentRepository.class);
            if (repository == null && !autoCreate) {
                // the existence check up front, with the configuration-level message
                throw new IllegalStateException("Ingestion pipeline '" + name
                        + "' references idempotent repository '" + repositoryName + "' but no such bean exists");
            }
            if (repository != null) {
                // whether auto-create is set or not, a pre-existing CDI-produced repository wins
                // and does not pass through the registry's bind hook, so a CamelContextAware
                // implementation would otherwise run contextless
                CamelContextAware.trySetCamelContext(repository, getContext());
            }
            definition.idempotentRepository(repositoryName)
                    .idempotentRepositoryAutoCreate(autoCreate);
        }
        return definition;
    }

    private static String required(String name, String value, String property) {
        if (value == null) {
            throw new IllegalStateException("Ingestion pipeline '" + name + "' has no " + property
                    + ". Set quarkus.camel.langchain4j.ingest." + name + "." + property);
        }
        return value;
    }

    private EmbeddingStore<TextSegment> resolveStore(String name, String configured) {
        return resolve(name, storeCandidates, configured, "embedding store", "embedding-store");
    }

    private EmbeddingModel resolveModel(String name, String configured) {
        return resolve(name, modelCandidates, configured, "embedding model", "embedding-model");
    }

    /**
     * CDI is the one mechanism for both lookups: the named path selects on the qualifier, the
     * unnamed path counts the candidates — through handles, so beans are not instantiated merely
     * to be counted. Picking one silently would bind a pipeline to whichever bean happened to be
     * discovered first. A raw-typed registry search cannot serve here: it never matches a bean
     * typed {@code EmbeddingStore<TextSegment>}.
     */
    private <T> T resolve(String name, Instance<T> candidates, String configured, String what, String property) {
        if (configured != null) {
            Instance<T> named = candidates.select(NamedLiteral.of(configured));
            if (named.isUnsatisfied()) {
                throw new IllegalStateException("Ingestion pipeline '" + name + "' references " + what + " '"
                        + configured + "' but no such bean exists");
            }
            return named.get();
        }
        List<Instance.Handle<T>> handles = StreamSupport.stream(candidates.handles().spliterator(), false)
                .collect(Collectors.toList());
        if (handles.isEmpty()) {
            throw new IllegalStateException("Ingestion pipeline '" + name + "' needs an " + what
                    + ", but no bean of that type exists. Define one, for example with a @Produces method.");
        }
        if (handles.size() > 1) {
            throw new IllegalStateException("Ingestion pipeline '" + name + "' found " + handles.size() + " "
                    + what + " beans. Name the one to use with quarkus.camel.langchain4j.ingest." + name + "."
                    + property);
        }
        return handles.get(0).get();
    }
}
