== Camel Quarkus Salesforce Integration Tests

By default, the Salesforce integration tests use WireMock to stub the API interactions.

IMPORTANT: Note that when using Wiremock, the Change Data Capture Events test is disabled.

To run `camel-quarkus-salesforce` integration tests using Salesforce API interactions, you must first create a Salesforce developer account https://developer.salesforce.com/.

Next create a new 'Connected App' from the app manager page. You may need to adjust the OAuth policy settings for
`Permitted Users` and also `IP Relaxation` rules, depending on your needs. Also enable Change Data Capture for the 'Account' entity by visiting the Integrations -> Change Data Capture page.

Next create a document named 'test'.

Next create a new Platform Event named `TestEvent`. Set Publish Behavior to `Publish Immediately`. Save and make sure the API name is `TestEvent__e`.

You can find the app OAuth settings by choosing the 'view' option from the app manager page. Then set the following environment variables.

[source,shell]
----
export SALESFORCE_CLIENTID=your-salesforce-client-id
export SALESFORCE_CLIENTSECRET=your-salesforce-client-secret
export SALESFORCE_USERNAME=your-salesforce-username
export SALESFORCE_PASSWORD=your-salesforce-password
----

To regenerate the Salesforce DTO classes, run `mvn clean generate-sources -Pgenerate-salesforce-dtos`.