/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.camel.quarkus.component.mina.sftp.it;

import java.nio.file.Files;
import java.nio.file.Path;

import io.quarkus.runtime.Startup;
import jakarta.enterprise.context.ApplicationScoped;
import org.jboss.logging.Logger;

import static java.nio.file.StandardCopyOption.*;

/**
 * Manages SSH certificates for MINA SFTP integration tests.
 * Uses certificates generated by the containerized SFTP test resource.
 */
@ApplicationScoped
@Startup
public class MinaSftpCertificateManager {
    private static final Logger LOGGER = Logger.getLogger(MinaSftpCertificateManager.class);

    private Path certsDir;

    public MinaSftpCertificateManager() {
        try {
            initializeCertificates();
        } catch (Exception e) {
            throw new RuntimeException("Failed to initialize MINA SFTP certificates", e);
        }
    }

    private void initializeCertificates() throws Exception {
        LOGGER.info("Setting up MINA SFTP certificate files from test resource");

        Path targetCerts = Path.of("target", "certs");
        Path classpathCerts = Path.of("target", "classes", "certs");
        Files.createDirectories(targetCerts);
        Files.createDirectories(classpathCerts);

        certsDir = targetCerts;

        String userKeyPath = System.getProperty("sftp.test.user.key");
        String userCertPath = System.getProperty("sftp.test.user.cert");
        String ftpKeyPath = System.getProperty("sftp.test.ftp.key");
        String ftpEncryptedKeyPath = System.getProperty("sftp.test.ftp.encrypted.key");

        if (userKeyPath == null || userCertPath == null || ftpKeyPath == null || ftpEncryptedKeyPath == null) {
            throw new IllegalStateException(
                    "Certificate paths not set. Test resource not started? sftp.test.user.key=" + userKeyPath
                            + ", sftp.test.user.cert=" + userCertPath
                            + ", sftp.test.ftp.key=" + ftpKeyPath
                            + ", sftp.test.ftp.encrypted.key=" + ftpEncryptedKeyPath);
        }

        byte[] privateKeyBytes = Files.readAllBytes(Path.of(userKeyPath));
        byte[] certificateBytes = Files.readAllBytes(Path.of(userCertPath));

        Files.write(targetCerts.resolve("test-key-rsa.key"), privateKeyBytes);
        Files.write(targetCerts.resolve("test-key-rsa-cert.pub"), certificateBytes);
        Files.write(classpathCerts.resolve("test-key-rsa.key"), privateKeyBytes);
        Files.write(classpathCerts.resolve("test-key-rsa-cert.pub"), certificateBytes);

        Path ftpKeySource = Path.of(ftpKeyPath);
        Files.copy(ftpKeySource, targetCerts.resolve("ftp.key"), REPLACE_EXISTING);
        Files.copy(ftpKeySource, classpathCerts.resolve("ftp.key"), REPLACE_EXISTING);

        Path ftpEncryptedKeySource = Path.of(ftpEncryptedKeyPath);
        Files.copy(ftpEncryptedKeySource, targetCerts.resolve("ftp-encrypted.key"),
                REPLACE_EXISTING);
        Files.copy(ftpEncryptedKeySource, classpathCerts.resolve("ftp-encrypted.key"),
                REPLACE_EXISTING);

        LOGGER.infof("MINA SFTP certificate files created in: %s and %s", targetCerts, classpathCerts);
    }

    public Path getCertsDir() {
        return certsDir;
    }

    public byte[] getUserPrivateKeyBytes() {
        try {
            String path = System.getProperty("sftp.test.user.key");
            if (path == null) {
                throw new IllegalStateException("Certificate path not set. Test resource not started?");
            }
            return Files.readAllBytes(Path.of(path));
        } catch (Exception e) {
            throw new RuntimeException("Failed to read user private key bytes", e);
        }
    }

    public byte[] getUserCertificateBytes() {
        try {
            String path = System.getProperty("sftp.test.user.cert");
            if (path == null) {
                throw new IllegalStateException("Certificate path not set. Test resource not started?");
            }
            return Files.readAllBytes(Path.of(path));
        } catch (Exception e) {
            throw new RuntimeException("Failed to read user certificate bytes", e);
        }
    }
}
