=== Special BOM

`camel-quarkus-spark` is special compared to other Camel Quarkus extensions which are managed in
`camel-quarkus-bom` together with their important dependencies. This is because the Camel Spark extension depends
on rather old versions of various libraries, that may conflict with their newer versions required by other Quarkus and
Camel Quarkus extensions. Therefore, `camel-quarkus-spark` extension and its dependencies are managed in a special
BOM called `camel-quarkus-spark-bom`.

For `camel-quarkus-spark` to work properly in end user applications, `camel-quarkus-spark-bom` need to be
imported before any other Quarkus or Camel Quarkus BOMs.

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-spark-bom</artifactId>
            <version>${camel-quarkus.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <!-- Other BOMs -->
        <dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-bom</artifactId>
            <version>${camel-quarkus.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

[WARNING]
====
The above setup will make `camel-quarkus-spark` work properly but it may break other extensions which are
sensitive to downgrades of the transitive dependencies done in `camel-quarkus-spark-bom`.
====
