= Apache Camel extensions for Quarkus Documentation

== Antora playbooks

There are two Antora playbooks available in the project: link:antora-playbook.yml[antora-playbook.yml] and
link:antora-playbook-dev.yml[antora-playbook-dev.yml].

link:antora-playbook.yml[antora-playbook.yml] is optimized for fast `xref` verification on the CI - it is used under
the hood by `exec-maven-plugin` when `mvn verify` is invoked. However, the site it produces is rather
incomplete.

link:antora-playbook-dev.yml[antora-playbook-dev.yml] aims at building a more complete site. It pulls Camel and Camel
Spring Boot Antora docs so that the lists of Camel components (available under Camel Quarkus reference docs) are built
too.


== Environment Setup

To setup the environment you need to execute the following command once (and every time you change yarn dependencies):

[code,shell]
----
yarn install
----

== Build the Documentation Website

To generate the documentation website, execute:

[code,shell]
----
yarn build
----

To preview it in the local browser, execute:

[code,shell]
----
yarn preview
----

To both build and preview, execute:

[code,shell]
----
yarn dev
----
