site:
  title: Apache Camel extensions for Quarkus
  url: https://camel.apache.org
  start_page: camel-quarkus::index.adoc
content:
  sources:
  - url: ../
    branches: HEAD
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./target/site
asciidoc:
  attributes:
    # Changes from here need to get ported to https://github.com/apache/camel-website/blob/master/site.yml
    camel-quarkus-last-release: 0.3.1
