This component is able to load XQuery definitions from classpath.
To make it work also in native mode, you need to explicitly embed the queries in the native executable
by using the `quarkus.native.resources.includes` property.

For instance, the two routes below load an XQuery script from two classpath resources named `myxquery.txt` and `another-xquery.txt` respectively:

[source,java]
----
from("direct:start").transform().xquery("resource:classpath:myxquery.txt", String.class);
from("direct:start").to("xquery:another-xquery.txt");
----

To include these (an possibly other queries stored in `.txt` files) in the native image, you would have to add something like the following to your `application.properties` file:

[source,properties]
----
quarkus.native.resources.includes = *.txt
----

More information about selecting resources for inclusion in the native executable can be found at xref:user-guide/native-mode.adoc#embedding-resource-in-native-executable[Embedding resource in native executable].