#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build PR

on:
  pull_request:
    branches:
      - master
      - camel-master
      - quarkus-master
    paths-ignore:
      - '**.adoc'
      - 'KEYS'
      - 'LICENSE.txt'
      - 'NOTICE.txt'

env:
  LANG: en_US

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set BRANCH_OPTIONS
        if: github.base_ref == 'camel-master' || github.base_ref == 'quarkus-master'
        run: |
          echo '::set-env name=BRANCH_OPTIONS::-Psnapshots'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: |
          ./mvnw -V -ntp ${BRANCH_OPTIONS} \
            clean install
      - name: Save Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ github.sha }}
          restore-keys: |
            maven-${{ github.sha }}
  build-alternative-jvm:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        java: [ '11' , '12' ]
    steps:
      - name: Set BRANCH_OPTIONS
        if: github.base_ref == 'camel-master' || github.base_ref == 'quarkus-master'
        run: |
          echo '::set-env name=BRANCH_OPTIONS::-Psnapshots'
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ github.sha }}
          restore-keys: |
            maven-${{ github.sha }}
      - name: Build on ${{ matrix.java }}
        run: |
          ./mvnw -V -ntp ${BRANCH_OPTIONS} \
            clean verify
  native-tests:
    name: Native Tests - ${{matrix.category}}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category: [Core, Foundation, Platform, Messaging, Dataformats, Networking, SQL, Cloud, Misc, SAAS, Memoryhog Dataformat JSON, Memoryhog Infinispan, Memoryhog Olingo4, Memoryhog XML]
        include:
          - category: Cloud
            test-modules: >
              aws
              azure
              consul
          - category: Core
            test-modules: >
              core
              core-impl
              core-main
              core-main-caffeine-lrucache
              core-main-collector
              core-main-xml-io
              core-main-xml-jaxb
          - category: Dataformats
            test-modules: >
              base64
              bindy
              csv
              dataformat
              jaxb
              xstream
              soap
          - category: Foundation
            test-modules: >
              bean
              controlbus
              exec
              file
              hystrix
              jsonpath
              scheduler
              seda
              ref
          - category: Memoryhog Dataformat JSON
            test-modules: >
              dataformats-json
          - category: Memoryhog Infinispan
            test-modules: >
              infinispan
          - category: Memoryhog Olingo4
            test-modules: >
              olingo4
          - category: Memoryhog XML
            test-modules: >
              xml
          - category: Messaging
            test-modules: >
              activemq
              kafka
              messaging
          - category: Misc
            test-modules: >
              bean-validator
              braintree
              compression
              dozer
              ftp
              graphql
              mail
              mustache
              pdf
              qute
              stream
              tarfile
              telegram
              validator
          - category: Networking
            test-modules: >
              http
              netty
              servlet
              websocket-jsr356
          - category: Platform
            test-modules: >
              microprofile
              opentracing
              platform-http
              platform-http-engine
              reactive-streams
          - category: SAAS
            test-modules: >
              box
              google
              jira
              salesforce
              slack
              twitter
          - category: SQL
            test-modules: >
              jdbc
              mongodb
              sql
    steps:
      - name: Set BRANCH_OPTIONS
        if: github.base_ref == 'camel-master' || github.base_ref == 'quarkus-master'
        run: |
          echo '::set-env name=BRANCH_OPTIONS::-Psnapshots'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-${{ github.sha }}
          restore-keys: |
            maven-${{ github.sha }}
      - name: Integration Tests
        env:
          TEST_MODULES: ${{matrix.test-modules}}
        run: |
          for i in $TEST_MODULES
          do modules+=("integration-tests/$i"); done
          IFS=,
          eval ./mvnw -V -ntp ${BRANCH_OPTIONS} clean verify \
            -Dnative \
            -Ddocker \
            -DskipTests \
            -pl "${modules[*]}"

  # memoryhogs:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set Up Java
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 1.8
  #     - name: Restore Cache
  #       uses: actions/cache@v1
  #       with:
  #         path: ~/.m2/repository
  #         key: maven-${{ github.sha }}
  #         restore-keys: |
  #           maven-${{ github.sha }}
  #     # run the :camel-quarkus-integration-test-fhir as standalone process
  #     # as it building the native image including camel-fhir requires lot
  #     # of memory this we nee to limit it to avoid the process fail for OOM.
  #     - name: Integration Tests
  #       run: |
  #         ./mvnw -V -B \
  #           -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify \
  #           -Dnative \
  #           -Ddocker \
  #           -DskipTests \
  #           -Dnative-image.xmx=5g \
  #           -pl :camel-quarkus-integration-test-fhir
